/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c4424826d1e16e41551a0ca79f35627f)
interface __BaseEnv_Env {
	ALLOWED_ORIGIN: "https://joshbeyondborders.org";
	GITHUB_OWNER: "kernbrent";
	GITHUB_REPO: "JoshBeyondBorders";
	GITHUB_BRANCH: "main";
	WORKBOOK_PATH: "admin/resources/giving-workbook.enc.json";
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_BRANCH" | "WORKBOOK_PATH" | "GITHUB_TOKEN">> {}
}
