/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5bf87fe4eface8b5e9d8ef73ff1f7e91)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGIN: "https://joshbeyondborders.org";
	GITHUB_OWNER: "kernbrent";
	GITHUB_REPO: "JoshBeyondBorders";
	GITHUB_BRANCH: "main";
	WORKBOOK_PATH: "admin/resources/giving-workbook.enc.json";
	PROGRESS_PATH: "data/giving-progress.json";
	GIVING_GOAL: "7500";
	PAYPAL_ITEM_TITLE: "Josh Beyond Borders Donation";
	PAYPAL_ITEM_ID: "BeyondBorders";
	PAYPAL_RECEIVER_EMAIL: "christianstepsministries@gmail.com";
	PAYPAL_LOOKBACK_DAYS: "93";
	GITHUB_TOKEN: string;
	PAYPAL_CLIENT_ID: string;
	PAYPAL_CLIENT_SECRET: string;
	CSM_DISTRIBUTION_SECRET: string;
	CSM_STATUS: Fetcher /* christian-steps-admin-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_BRANCH" | "WORKBOOK_PATH" | "PROGRESS_PATH" | "GIVING_GOAL" | "PAYPAL_ITEM_TITLE" | "PAYPAL_ITEM_ID" | "PAYPAL_RECEIVER_EMAIL" | "PAYPAL_LOOKBACK_DAYS" | "GITHUB_TOKEN" | "PAYPAL_CLIENT_ID" | "PAYPAL_CLIENT_SECRET" | "CSM_DISTRIBUTION_SECRET">> {}
}
